# Generated by Django 6.0.3 on 2026-03-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_syllabusplan_lecture_topic_syllabusprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_marks', models.PositiveIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_types', to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.subject')),
                ('mark_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.marktype')),
            ],
            options={
                'unique_together': {('student', 'subject', 'mark_type')},
            },
        ),
    ]
