# Generated by Django 5.1 on 2026-03-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_resourcefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
