# Generated by Django 5.1 on 2026-03-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timetable_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='subject_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], default='Theory', max_length=10),
        ),
    ]
