# Generated by Django 5.1 on 2026-03-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_timetable_subject_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabusplan',
            name='subject',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('co_covered', models.CharField(blank=True, max_length=50)),
                ('total_lectures_required', models.PositiveIntegerField(default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LecturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.PositiveIntegerField()),
                ('topic_name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_plans', to='core.subject')),
            ],
            options={
                'ordering': ['lecture_number'],
                'unique_together': {('subject', 'lecture_number')},
            },
        ),
        migrations.AlterField(
            model_name='lecture',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lectureplan'),
        ),
        migrations.DeleteModel(
            name='SyllabusProgress',
        ),
        migrations.DeleteModel(
            name='SyllabusPlan',
        ),
    ]
