# Generated by Django 5.1 on 2026-03-31 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_subject_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('student', 'subject')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='division',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.batch'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.division'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('roll_number', 'subject', 'division'), ('student', 'subject')},
        ),
    ]
