# Generated by Django 5.1 on 2026-03-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='exam_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='max_marks',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='mark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='marks_obtained',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_type',
        ),
        migrations.DeleteModel(
            name='MarkType',
        ),
    ]
