# Generated by Django 5.1 on 2026-03-31 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_mark_unique_together_mark_created_at_mark_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='marks_obtained',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mark',
            name='max_marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject', 'exam_type')},
        ),
    ]
