# Generated by Django 5.1 on 2026-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_marks_practicalmark_theorymark_delete_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='has_assignments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_mini_project',
            field=models.BooleanField(default=False),
        ),
    ]
