# Generated by Django 5.1 on 2026-04-02 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_subject_has_assignments_subject_has_mini_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('lecture_reminder', 'Lecture Reminder'), ('attendance_alert', 'Attendance Alert'), ('marks_alert', 'Marks Alert'), ('syllabus_alert', 'Syllabus Alert'), ('system_alert', 'System Alert')], default='system_alert', max_length=20),
        ),
    ]
